server:
  port: 8080
  name: web-server
  hosts:
    - 1
    - 2
  ratio: 0.5
  profile:
    username: admin
    password: pwd
services:
  - name: service1
    url: http://localhost:8081
    timeout: 5000
  - name: service2
    url: http://localhost:8082
    timeout: 5000
flashboot:
  datasource:
    mysql:
      host: localhost
      port: 3306
      user: root
      password: e9Epsdji1192@
      database: flashboot
      charset: utf8mb4